language: php

php:
    - 7.3
    - 8.0

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.4
          env: SYMFONY_VERSION=4.4.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 8.0
          env: SYMFONY_VERSION=5.2.*

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - COMPOSER_FLAGS="--prefer-dist"

before_script:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update $COMPOSER_FLAGS --no-interaction
